spring.profiles.default: dev
---
server:
  port: 1234

spring:
  profiles:
    active: dev
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_HOST}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  #    defer-datasource-initialization: true

  #  sql:
  #    init:
  #      mode: always
  #      data-locations: classpath:db/data.sql

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
      folder: files/
    stack:
      auto: false
    region:
      static: ${AWS_REGION}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

logging:
  level:
    org.hibernate.SQL: TRACE

